apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elastic
  namespace: sensu-system
spec:
  replicas: 1
  template:
    metadata:
      name: elastic
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: elasticsearch:7.4.2
          ports:
            - protocol: TCP
              containerPort: 9200
            - protocol: TCP
              containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
        - name: sensu-agent
          image: sensu/sensu:5.14.2
          command: ["/opt/sensu/bin/sensu-agent", "start", "--log-level", "debug"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://sensu.sensu-system.svc.cluster.local:8081
            - name: SENSU_NAMESPACE
              value: default
            - name: SENSU_SUBSCRIPTIONS
              value: elastic
            - name: SENSU_DEREGISTER
              value: "true"
            - name: SENSU_STATSD_EVENT_HANDLERS
              value: statsd
---
apiVersion: v1
kind: Service
metadata:
  name: elastic
  namespace: sensu-system
spec:
  selector:
    app: elastic
  type: LoadBalancer
  ports:
    - name: api
      protocol: TCP
      port: 9200
      targetPort: 9200
